"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { ProductCategory } from "@/types/product";
export default function CatalogFilters({ categories }: { categories: ProductCategory[] }) {
  const router = useRouter(); const current = useSearchParams(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(current.get("q") ?? "");
  const set = (key: string, value: string) => { const params = new URLSearchParams(current.toString()); if (value) params.set(key,value); else params.delete(key); router.push(`/tienda?${params.toString()}`); };
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const params = new URLSearchParams(current.toString());
    const submittedQuery = String(new FormData(event.currentTarget).get("q") ?? "").trim();
    if (submittedQuery) params.set("q", submittedQuery); else params.delete("q");
    router.push(`/tienda?${params.toString()}`);
  };
  const clear = () => { setQuery(""); router.push("/tienda"); };
  const controls = <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Categoría<select value={current.get("categoria") ?? ""} onChange={(e)=>set("categoria",e.target.value)} className="field py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">Todas las categorías</option>{categories.map((category)=><option value={category.slug} key={category.id}>{category.name}</option>)}</select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Disponibilidad<select value={current.get("stock") ?? ""} onChange={(e)=>set("stock",e.target.value)} className="field py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">Todo el stock</option><option value="in-stock">Solo disponible</option></select></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Ordenar<select value={current.get("orden") ?? "featured"} onChange={(e)=>set("orden",e.target.value)} className="field py-2.5 text-sm font-medium normal-case tracking-normal"><option value="featured">Recomendados</option><option value="price-asc">Menor precio</option><option value="price-desc">Mayor precio</option><option value="name">Nombre A–Z</option></select></label><div className="grid grid-cols-2 gap-2"><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Desde<input type="number" min="0" defaultValue={current.get("min") ?? ""} onBlur={(e)=>set("min",e.target.value)} className="field py-2.5 text-sm font-medium" placeholder="S/ 0"/></label><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Hasta<input type="number" min="0" defaultValue={current.get("max") ?? ""} onBlur={(e)=>set("max",e.target.value)} className="field py-2.5 text-sm font-medium" placeholder="S/ 9999"/></label></div></div>;
  return <div className="panel p-3 sm:p-4"><div className="flex gap-3"><form onSubmit={submit} className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={17}/><input name="q" className="field py-2.5 pl-9 text-sm" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Busca por nombre o SKU" aria-label="Buscar en catálogo"/></form><button onClick={()=>setOpen(!open)} className="btn-secondary focus-ring px-3 lg:hidden" aria-expanded={open}><SlidersHorizontal size={18}/><span className="hidden sm:inline">Filtros</span></button><button onClick={clear} className="focus-ring hidden rounded-xl px-3 text-sm font-bold text-slate-400 hover:text-orange-300 lg:inline-flex" aria-label="Limpiar filtros"><X size={16}/> Limpiar</button></div><div className="mt-4 hidden lg:block">{controls}</div>{open && <div className="mt-4 border-t border-white/8 pt-4 lg:hidden">{controls}<button onClick={()=>setOpen(false)} className="btn-primary mt-4 w-full">Aplicar filtros</button></div>}<div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Filter size={13}/>Los filtros se guardan en la URL para que puedas compartir tu selección.</div></div>;
}
