"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check, ShoppingBag, Zap } from "lucide-react";
import { m } from "motion/react";
import { Product } from "@/types/product";
import { formatPrice } from "@/lib/utils/formatPrice";
import { getPriceValue } from "@/lib/utils/price";
import { useCartStore } from "@/store/cartStore";

export default function ProductCard({ product, priority = false }: { product: Product; priority?: boolean }) {
  const addItem = useCartStore((state) => state.addItem);
  const stock = product.stockStatus === "IN_STOCK"; const category = product.productCategories?.nodes[0]?.name ?? "Hardware"; const sale = getPriceValue(product.regularPrice) > getPriceValue(product.price); const hasVariations = Boolean(product.variations?.nodes.length);
  const quickAdd = () => { if (!stock || hasVariations) return; addItem({ id: product.id, productId: product.databaseId, name: product.name, price: getPriceValue(product.price), quantity: 1, image: product.image?.sourceUrl, category }); };
  return <m.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .18 }} transition={{ duration: .42 }} className="group relative min-w-0"><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0d121d] transition hover:-translate-y-1 hover:border-orange-400/55 hover:shadow-[0_22px_55px_rgba(0,0,0,.35)]"><Link href={`/producto/${product.slug}`} className="focus-ring block"><div className="relative aspect-[1/.84] overflow-hidden bg-gradient-to-br from-slate-800 to-slate-950"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(57,216,255,.14),transparent_48%)]" />{product.image ? <Image src={product.image.sourceUrl} alt={product.image.altText || product.name} fill priority={priority} sizes="(max-width: 640px) 90vw, (max-width: 1024px) 45vw, 25vw" className="object-cover transition duration-500 group-hover:scale-[1.055]" /> : <div className="grid h-full place-items-center text-center"><div className="rounded-full border border-white/10 bg-white/5 p-5 text-slate-500"><Zap size={28} /></div></div>}<div className="absolute left-3 top-3 flex gap-2"><span className="rounded-full border border-white/10 bg-[#090d15]/80 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-200 backdrop-blur">{category}</span>{sale ? <span className="rounded-full bg-orange-400 px-2.5 py-1 text-[10px] font-black text-slate-950">Oferta</span> : null}</div><span className={`absolute bottom-3 left-3 inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold backdrop-blur ${stock ? "bg-emerald-400/13 text-emerald-300" : "bg-rose-400/13 text-rose-300"}`}>{stock ? <Check size={12} /> : null}{stock ? "Disponible" : "Agotado"}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="min-h-11 text-sm font-bold leading-5 text-slate-100 transition group-hover:text-orange-200">{product.name}</h3><ArrowUpRight size={17} className="mt-0.5 shrink-0 text-slate-500 transition group-hover:text-orange-300" /></div><div className="mt-4"><p className="price text-xl">{formatPrice(product.price)}</p>{sale ? <p className="mt-1 text-xs text-slate-500 line-through">{formatPrice(product.regularPrice)}</p> : null}</div></div></Link><div className="flex items-center justify-between border-t border-white/8 px-4 py-3"><span className="text-[11px] text-slate-500">{hasVariations ? "Elige una variante" : "Añadir rápidamente"}</span><button onClick={quickAdd} disabled={!stock || hasVariations} className="focus-ring rounded-xl border border-white/10 bg-white/5 p-2.5 text-slate-200 transition hover:border-orange-400 hover:bg-orange-400 hover:text-slate-950 disabled:cursor-not-allowed disabled:opacity-35" aria-label={hasVariations ? "Selecciona una variante en el detalle" : `Agregar ${product.name} al carrito`}><ShoppingBag size={17} /></button></div></div></m.article>;
}
