"use client";

import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Gamepad2, Palette, Sparkles } from "lucide-react";
import { AnimatePresence, m, useReducedMotion } from "motion/react";
import { useState } from "react";

const modes = [{ id: "gaming", label: "Gaming", icon: Gamepad2, title: "Domina cada partida con una build a tu medida.", text: "Prioriza gráficos fluidos, respuesta rápida y una base lista para tus próximos upgrades.", chips: ["FPS competitivo", "Ray tracing", "Streaming"] }, { id: "creator", label: "Creación", icon: Palette, title: "Convierte cada idea en tiempo bien aprovechado.", text: "Elige equilibrio entre procesador, memoria y almacenamiento para proyectos que no pueden esperar.", chips: ["Edición", "Render", "Diseño 3D"] }, { id: "work", label: "Trabajo", icon: BriefcaseBusiness, title: "Un setup que sigue tu ritmo todos los días.", text: "Configuraciones confiables y ágiles para productividad, estudio y multitarea sin ruido innecesario.", chips: ["Productividad", "Multitarea", "Home office"] }];

export default function UseCaseExplorer() { const [active, setActive] = useState("gaming"); const selected = modes.find((mode) => mode.id === active) ?? modes[0]; const reduce = useReducedMotion(); const Icon = selected.icon; return <section className="mx-auto max-w-7xl px-6 pb-20"><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#0b101b]"><div className="grid lg:grid-cols-[.78fr_1.22fr]"><div className="border-b border-white/8 p-7 sm:p-10 lg:border-b-0 lg:border-r"><p className="eyebrow">Encuentra tu enfoque</p><h2 className="font-display mt-3 text-4xl font-bold">¿Qué quieres que haga tu próxima PC?</h2><p className="mt-4 text-sm leading-6 text-slate-400">Explora un punto de partida y deja que el armador te acompañe con las piezas que necesitas.</p><div className="mt-7 grid gap-2">{modes.map((mode) => { const ModeIcon = mode.icon; const selectedMode = mode.id === active; return <button key={mode.id} aria-pressed={selectedMode} onClick={() => setActive(mode.id)} className={`focus-ring flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold transition ${selectedMode ? "bg-orange-400 text-slate-950 shadow-[0_8px_25px_rgba(255,106,0,.18)]" : "bg-white/[.035] text-slate-300 hover:bg-white/[.08]"}`}><ModeIcon size={18}/>{mode.label}<ArrowRight size={16} className={`ml-auto transition ${selectedMode ? "translate-x-1" : ""}`}/></button>; })}</div></div><div className="relative min-h-[330px] overflow-hidden p-7 sm:p-10"><AnimatePresence mode="wait"><m.div key={selected.id} initial={reduce ? { opacity: 0 } : { opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={reduce ? { opacity: 0 } : { opacity: 0, x: -18 }} transition={{ duration: .35 }} className="relative z-10"><div className="grid size-12 place-items-center rounded-2xl border border-orange-300/25 bg-orange-400/10 text-orange-300"><Icon size={24}/></div><h3 className="font-display mt-7 max-w-xl text-4xl font-bold leading-tight">{selected.title}</h3><p className="mt-4 max-w-xl leading-7 text-slate-400">{selected.text}</p><div className="mt-7 flex flex-wrap gap-2">{selected.chips.map((chip, index) => <m.span key={chip} initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .16 + index * .07 }} className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs font-bold text-slate-200">{chip}</m.span>)}</div><Link href="/arma-tu-pc" className="btn-primary focus-ring mt-8">Explorar mi configuración <ArrowRight size={17}/></Link></m.div></AnimatePresence><div className="absolute -right-20 -top-16 size-80 rounded-full bg-orange-500/13 blur-3xl"/><div className="orbital-ring absolute -bottom-20 right-8 size-64 rounded-full border border-cyan-300/20"/><Sparkles className="absolute bottom-12 right-16 text-cyan-200/50" size={38}/></div></div></div></section>; }
